/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package go_client;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author osman
 */
public class Game extends javax.swing.JFrame implements MouseListener {

    public static Game ThisGame;
    ImageIcon board = new ImageIcon("go_board.png");
    ImageIcon piece_white = new ImageIcon("piece_white.png");
    JLabel lbl_board = new JLabel(board);
    JLayeredPane lp_board = new JLayeredPane();
    JButton btn_connect = new JButton("Connect");
    JTextField txt_name = new JTextField("Name");
    JTextField txt_rival_name = new JTextField("Rival");
    JTextArea txt_send = new JTextArea();
    JButton btn_send_message = new JButton("Send");
    JTextArea txt_receive = new JTextArea();
    
    JLabel[] pieces = new JLabel[36];
    JLabel piece1 = new JLabel(piece_white);
    /*JLabel piece2 = new JLabel();
    JLabel piece3 = new JLabel();
    JLabel piece4 = new JLabel();
    JLabel piece5 = new JLabel();
    JLabel piece6 = new JLabel();
    JLabel piece7 = new JLabel();
    JLabel piece8 = new JLabel();
    JLabel piece9 = new JLabel();
    JLabel piece10 = new JLabel();
    JLabel piece11 = new JLabel();
    JLabel piece12 = new JLabel();
    JLabel piece13 = new JLabel();
    JLabel piece14 = new JLabel();
    JLabel piece15 = new JLabel();
    JLabel piece16 = new JLabel();
    JLabel piece17 = new JLabel();
    JLabel piece18 = new JLabel();
    JLabel piece19 = new JLabel();
    JLabel piece20 = new JLabel();
    JLabel piece21 = new JLabel();
    JLabel piece22 = new JLabel();
    JLabel piece23 = new JLabel();
    JLabel piece24 = new JLabel();
    JLabel piece25 = new JLabel();
    JLabel piece26 = new JLabel();
    JLabel piece27 = new JLabel();
    JLabel piece28 = new JLabel();
    JLabel piece29 = new JLabel();
    JLabel piece30 = new JLabel();
    JLabel piece31 = new JLabel();
    JLabel piece32 = new JLabel();
    JLabel piece33 = new JLabel();
    JLabel piece34 = new JLabel();
    JLabel piece35 = new JLabel();
    JLabel piece36 = new JLabel();*/
    
    int[] pointer;

    /**
     * Creates new form Frm_go
     */
    public Game() {

        pointer = new int[2];
        initComponents();
        ThisGame = this;

        txt_name.setBounds(20, 20, 80, 25);
        ThisGame.add(txt_name);

        btn_connect.setBounds(130, 20, 80, 25);
        ThisGame.add(btn_connect);

        txt_rival_name.setBounds(240, 20, 80, 25);
        txt_rival_name.setBackground(new Color(221, 221, 221));
        txt_rival_name.setEditable(false);
        ThisGame.add(txt_rival_name);

        txt_send.setBounds(20, 380, 100, 60);
        ThisGame.add(txt_send);

        btn_send_message.setBounds(140, 380, 60, 25);
        ThisGame.add(btn_send_message);

        txt_receive.setBounds(220, 380, 100, 60);
        ThisGame.add(txt_receive);

        lbl_board.setBounds(0, 0, 300, 300);

        lp_board.add(lbl_board, Integer.valueOf(0));
        lp_board.setBounds(20, 60, 300, 300);
        ThisGame.add(lp_board);

        for (int i = 0; i < 6; i++) {
            for (int j = 0; j < 6; j++) {
                pieces[i+j] = new JLabel(piece_white);
                pieces[i+j].setBounds(24+(43*j), 24+(43*i), 36, 36);
                pieces[i+j].setBackground(Color.red);
                lp_board.add(pieces[i+j], Integer.valueOf(1));
            }
        }
        
        //piece1.setBounds(15, 15, 30, 30);
        //lp_board.add(piece1,Integer.valueOf(1));

        ThisGame.setBounds(0, 0, 350, 500);

        lbl_board.addMouseListener(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btn_connectActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Client.Start("localhost", 2000);
        //başlangıç durumları

        btn_connect.setEnabled(false);
        txt_name.setEnabled(false);

        btn_send_message.setEnabled(false);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void mouseClicked(MouseEvent e) {
        int x = e.getX();
        int y = e.getY();
        System.out.println(x + "," + y);
    }

    @Override
    public void mousePressed(MouseEvent e) {

    }

    @Override
    public void mouseReleased(MouseEvent e) {

    }

    @Override
    public void mouseEntered(MouseEvent e) {

    }

    @Override
    public void mouseExited(MouseEvent e) {

    }
}
